---
name: Procedimientos
locale: es
type: learning
beta: false
teacher_info: ''
language: gobstones
id_format: "%05d"
order:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 9
  - 10
  - 11
  - 6
  - 7
  - 8
private: false
